/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheoRouteImport } from './routes/theo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TheoIndexRouteImport } from './routes/theo/index'
import { Route as TheoVideoIdRouteImport } from './routes/theo/video/$id'
import { Route as TheoSponsorIdRouteImport } from './routes/theo/sponsor/$id'

const TheoRoute = TheoRouteImport.update({
  id: '/theo',
  path: '/theo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoIndexRoute = TheoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TheoRoute,
} as any)
const TheoVideoIdRoute = TheoVideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => TheoRoute,
} as any)
const TheoSponsorIdRoute = TheoSponsorIdRouteImport.update({
  id: '/sponsor/$id',
  path: '/sponsor/$id',
  getParentRoute: () => TheoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/theo': typeof TheoRouteWithChildren
  '/theo/': typeof TheoIndexRoute
  '/theo/sponsor/$id': typeof TheoSponsorIdRoute
  '/theo/video/$id': typeof TheoVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/theo': typeof TheoIndexRoute
  '/theo/sponsor/$id': typeof TheoSponsorIdRoute
  '/theo/video/$id': typeof TheoVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/theo': typeof TheoRouteWithChildren
  '/theo/': typeof TheoIndexRoute
  '/theo/sponsor/$id': typeof TheoSponsorIdRoute
  '/theo/video/$id': typeof TheoVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/theo' | '/theo/' | '/theo/sponsor/$id' | '/theo/video/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/theo' | '/theo/sponsor/$id' | '/theo/video/$id'
  id:
    | '__root__'
    | '/'
    | '/theo'
    | '/theo/'
    | '/theo/sponsor/$id'
    | '/theo/video/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TheoRoute: typeof TheoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theo': {
      id: '/theo'
      path: '/theo'
      fullPath: '/theo'
      preLoaderRoute: typeof TheoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theo/': {
      id: '/theo/'
      path: '/'
      fullPath: '/theo/'
      preLoaderRoute: typeof TheoIndexRouteImport
      parentRoute: typeof TheoRoute
    }
    '/theo/video/$id': {
      id: '/theo/video/$id'
      path: '/video/$id'
      fullPath: '/theo/video/$id'
      preLoaderRoute: typeof TheoVideoIdRouteImport
      parentRoute: typeof TheoRoute
    }
    '/theo/sponsor/$id': {
      id: '/theo/sponsor/$id'
      path: '/sponsor/$id'
      fullPath: '/theo/sponsor/$id'
      preLoaderRoute: typeof TheoSponsorIdRouteImport
      parentRoute: typeof TheoRoute
    }
  }
}

interface TheoRouteChildren {
  TheoIndexRoute: typeof TheoIndexRoute
  TheoSponsorIdRoute: typeof TheoSponsorIdRoute
  TheoVideoIdRoute: typeof TheoVideoIdRoute
}

const TheoRouteChildren: TheoRouteChildren = {
  TheoIndexRoute: TheoIndexRoute,
  TheoSponsorIdRoute: TheoSponsorIdRoute,
  TheoVideoIdRoute: TheoVideoIdRoute,
}

const TheoRouteWithChildren = TheoRoute._addFileChildren(TheoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TheoRoute: TheoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
