/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as TheoRouteImport } from './routes/theo'
import { Route as DavisRouteImport } from './routes/davis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TheoIndexRouteImport } from './routes/theo/index'
import { Route as DavisIndexRouteImport } from './routes/davis/index'
import { Route as TheoVideoIdRouteImport } from './routes/theo/video/$id'
import { Route as TheoSponsorIdRouteImport } from './routes/theo/sponsor/$id'
import { Route as DavisVideoIdRouteImport } from './routes/davis/video/$id'
import { Route as DavisSponsorIdRouteImport } from './routes/davis/sponsor/$id'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoRoute = TheoRouteImport.update({
  id: '/theo',
  path: '/theo',
  getParentRoute: () => rootRouteImport,
} as any)
const DavisRoute = DavisRouteImport.update({
  id: '/davis',
  path: '/davis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoIndexRoute = TheoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TheoRoute,
} as any)
const DavisIndexRoute = DavisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DavisRoute,
} as any)
const TheoVideoIdRoute = TheoVideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => TheoRoute,
} as any)
const TheoSponsorIdRoute = TheoSponsorIdRouteImport.update({
  id: '/sponsor/$id',
  path: '/sponsor/$id',
  getParentRoute: () => TheoRoute,
} as any)
const DavisVideoIdRoute = DavisVideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => DavisRoute,
} as any)
const DavisSponsorIdRoute = DavisSponsorIdRouteImport.update({
  id: '/sponsor/$id',
  path: '/sponsor/$id',
  getParentRoute: () => DavisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/davis': typeof DavisRouteWithChildren
  '/theo': typeof TheoRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/davis/': typeof DavisIndexRoute
  '/theo/': typeof TheoIndexRoute
  '/davis/sponsor/$id': typeof DavisSponsorIdRoute
  '/davis/video/$id': typeof DavisVideoIdRoute
  '/theo/sponsor/$id': typeof TheoSponsorIdRoute
  '/theo/video/$id': typeof TheoVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/davis': typeof DavisIndexRoute
  '/theo': typeof TheoIndexRoute
  '/davis/sponsor/$id': typeof DavisSponsorIdRoute
  '/davis/video/$id': typeof DavisVideoIdRoute
  '/theo/sponsor/$id': typeof TheoSponsorIdRoute
  '/theo/video/$id': typeof TheoVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/davis': typeof DavisRouteWithChildren
  '/theo': typeof TheoRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/davis/': typeof DavisIndexRoute
  '/theo/': typeof TheoIndexRoute
  '/davis/sponsor/$id': typeof DavisSponsorIdRoute
  '/davis/video/$id': typeof DavisVideoIdRoute
  '/theo/sponsor/$id': typeof TheoSponsorIdRoute
  '/theo/video/$id': typeof TheoVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/davis'
    | '/theo'
    | '/unlock'
    | '/davis/'
    | '/theo/'
    | '/davis/sponsor/$id'
    | '/davis/video/$id'
    | '/theo/sponsor/$id'
    | '/theo/video/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unlock'
    | '/davis'
    | '/theo'
    | '/davis/sponsor/$id'
    | '/davis/video/$id'
    | '/theo/sponsor/$id'
    | '/theo/video/$id'
  id:
    | '__root__'
    | '/'
    | '/davis'
    | '/theo'
    | '/unlock'
    | '/davis/'
    | '/theo/'
    | '/davis/sponsor/$id'
    | '/davis/video/$id'
    | '/theo/sponsor/$id'
    | '/theo/video/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DavisRoute: typeof DavisRouteWithChildren
  TheoRoute: typeof TheoRouteWithChildren
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theo': {
      id: '/theo'
      path: '/theo'
      fullPath: '/theo'
      preLoaderRoute: typeof TheoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/davis': {
      id: '/davis'
      path: '/davis'
      fullPath: '/davis'
      preLoaderRoute: typeof DavisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theo/': {
      id: '/theo/'
      path: '/'
      fullPath: '/theo/'
      preLoaderRoute: typeof TheoIndexRouteImport
      parentRoute: typeof TheoRoute
    }
    '/davis/': {
      id: '/davis/'
      path: '/'
      fullPath: '/davis/'
      preLoaderRoute: typeof DavisIndexRouteImport
      parentRoute: typeof DavisRoute
    }
    '/theo/video/$id': {
      id: '/theo/video/$id'
      path: '/video/$id'
      fullPath: '/theo/video/$id'
      preLoaderRoute: typeof TheoVideoIdRouteImport
      parentRoute: typeof TheoRoute
    }
    '/theo/sponsor/$id': {
      id: '/theo/sponsor/$id'
      path: '/sponsor/$id'
      fullPath: '/theo/sponsor/$id'
      preLoaderRoute: typeof TheoSponsorIdRouteImport
      parentRoute: typeof TheoRoute
    }
    '/davis/video/$id': {
      id: '/davis/video/$id'
      path: '/video/$id'
      fullPath: '/davis/video/$id'
      preLoaderRoute: typeof DavisVideoIdRouteImport
      parentRoute: typeof DavisRoute
    }
    '/davis/sponsor/$id': {
      id: '/davis/sponsor/$id'
      path: '/sponsor/$id'
      fullPath: '/davis/sponsor/$id'
      preLoaderRoute: typeof DavisSponsorIdRouteImport
      parentRoute: typeof DavisRoute
    }
  }
}

interface DavisRouteChildren {
  DavisIndexRoute: typeof DavisIndexRoute
  DavisSponsorIdRoute: typeof DavisSponsorIdRoute
  DavisVideoIdRoute: typeof DavisVideoIdRoute
}

const DavisRouteChildren: DavisRouteChildren = {
  DavisIndexRoute: DavisIndexRoute,
  DavisSponsorIdRoute: DavisSponsorIdRoute,
  DavisVideoIdRoute: DavisVideoIdRoute,
}

const DavisRouteWithChildren = DavisRoute._addFileChildren(DavisRouteChildren)

interface TheoRouteChildren {
  TheoIndexRoute: typeof TheoIndexRoute
  TheoSponsorIdRoute: typeof TheoSponsorIdRoute
  TheoVideoIdRoute: typeof TheoVideoIdRoute
}

const TheoRouteChildren: TheoRouteChildren = {
  TheoIndexRoute: TheoIndexRoute,
  TheoSponsorIdRoute: TheoSponsorIdRoute,
  TheoVideoIdRoute: TheoVideoIdRoute,
}

const TheoRouteWithChildren = TheoRoute._addFileChildren(TheoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DavisRoute: DavisRouteWithChildren,
  TheoRoute: TheoRouteWithChildren,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
